# S02 T04: Pràctica amb programació numèrica

### Ex1
##### Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np

def calc (matriu):
    res=matriu.mean()
    print("Mitja: ",res)
    res=matriu.var()
    print("Variant: ",res)
    res=matriu.std()
    print("Desviació Típica: ",res)

# 2 arrays: una 1D (coorecta) i una 3x4 (incorrecta)
arr = np.array ([1,2,3,4,5,6,7,8])
arr_wrong = np.array([[ 0.0,  0.0,  0.0],[10.0, 10.0, 10.0],[20.0, 20.0, 20.0],[30.0, 30.0, 30.0]])

a = str(input("Decideixi quina array vol usar: 1D(premi G) or Wrong(B)")).upper()
if a == "G":
    arr_final = arr
else:
    arr_final = arr_wrong


if arr_final.ndim ==1:
    calc(arr_final)
else:
    print("Error: només podem procesar matrius 1D")

Mitja:  4.5
Variant:  5.25
Desviació Típica:  2.29128784747792


### Ex2
##### Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [2]:
np.random.randint(0,100,size=(3,3))

array([[10, 21, 86],
       [60, 89,  6],
       [13, 18,  6]])

### Ex3  
##### Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [3]:
taula = np.random.randint(0,100,size=(2,2))
print (taula)
print ("Total per Columna = {}".format(np.sum(taula, axis=0)))
print ("Total per Fila = {}".format(np.sum(taula, axis=1)))

[[90 25]
 [96 43]]
Total per Columna = [186  68]
Total per Fila = [115 139]


### Ex4
##### Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.
###### Coeficient de correlació = l'associació lineal entre variables.
###### Valor -1 = correlació negativa completa
###### Valor 0 = sense correlació 
###### Valor 0.0-0.4 = correlació  dèbil
###### Valor 0.4-0.6 = correlació  moderada
###### Valor 0.6-0.8 = correlació  forta
###### Valor 1 = correlació possitiva completa

###### Correlació de Pearson:
###### Davant de dues variables aleatoòries, X & Y.
###### si (σXY) es la covariança entre X i Yy (σX) és la desviació standard de X
######  Covariança (X- mitja de X) * (Y- mitja d'Y) es suma a cada valor i es divideix pel tamany de la mostra
###### coeficient de correlació = rho_ {X, Y} = frac { sigma_ {XY}} { sigma_X sigma_Y}
###### Coeficient = covariança / arrel quadrada del producte de les variances de X & Y

In [4]:
kgs= [72,76,78,81,89,95,108,115,120,130] # pes de 10 pacients
tensio = [115,121,125,130,141,150,165,170,177,178] # Tensió arterial sistòlica (mm Hg)
x=kgs
y=tensio

x_prom = np.sum(x)/len(x)
y_prom = np.sum(y)/len(y)
for a in range(len(x)):
    x1 = x-x_prom
for a in range(len(y)):
    y1 = y-y_prom


# x*y
xy = []
for a in range(len(x)):
    xy.insert(a,x[a] * y[a])
x2=[]
for a in range(len(x)):
    x2.insert(a,x[a] * x[a])
y2=[]
for a in range(len(y)):
    y2.insert(a, y[a] * y[a])

#totals  
sumx = np.sum(x)
sumy = np.sum(y)
sumxy = np.sum(xy)
sumx2 = np.sum(x2)
sumy2 = np.sum(y2)
#mitjanes
mediax= sumx/len(x)
mediay= sumy/len(y)

covariança = (sumxy/len(x)) -(mediax*mediay)

print("Covariança: {}".format(covariança))

#desviacions 
desx = np.sqrt((sumx2/len(x))-(mediax*mediax))
desy = np.sqrt((sumy2/len(y))-(mediay*mediay))

corr_Pearson = covariança / (desx*desy)
print ("Correlació: {}".format(corr_Pearson))
print ("Molt ALTA correlació possitiva!")


Covariança: 440.4200000000001
Correlació: 0.9864259364005639
Molt ALTA correlació possitiva!


In [5]:
# usant la funció corrcoef de numpy
# https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html
 
print(np.mean(np.multiply((x-np.mean(x)),(y-np.mean(y))))/(np.std(y)*np.std(x))) 
print(np.corrcoef(x,y))
print ("Molt ALTA correlació possitiva!")

0.986425936400566
[[1.         0.98642594]
 [0.98642594 1.        ]]
Molt ALTA correlació possitiva!
